### PR TITLE
Make supermarket and graphite sections optional

### PR DESCRIPTION
**Pull request by iroller**
We should be able to skip these sections by setting attribute value to nil.

### CODE REVIEW

**Comment by iroller** [comment]
Hm... however I'm not sure if chef-guard itself will work fine if we remove those sections.

**Comment by svanharmelen** [comment]
I think it does... But you should be able to test this by editing your config manually first and then let Chef-Guard run for a few...

**Comment by iroller** [comment]
@svanharmelen testing, will report back in a few

**Comment by iroller** [comment]
Having a separate issue (lot's of configuration changes, not sure which one causes it so far)
```
ERROR:   2015/04/21 19:28:12 Failed to create a new ChefGuard structure: Failed to create new Chef API connection: block size invalid for ''
```

I'll test this one once I figure it out.

**Comment by svanharmelen** [comment]
Hmm... Never saw that one before. I'm on IRC in case you want to discuss anything

**Comment by iroller** [comment]
Tested chef-guard with no supermarket and graphite sections - looks to be working fine, no errors.

**Pull request merged**
